### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by jordijoangimenez** [5G-MAG/rt-5gms-common-android-library#28]
Suggest adding a sentence saying that we use version 1.0.0 just as an example. The exact version needs to be checked.

Another option is to update all according to e.g. implementation 'com.fivegmag:a5gmscommonlibrary:1.2.0'

This has dependencies in the readmes of 
https://github.com/5G-MAG/rt-5gms-media-stream-handler
https://github.com/5G-MAG/rt-5gms-media-session-handler

I suggest something practical so we do not need to be after this all the time we have a new version of the common library.

**Comment by dsilhavy** [comment]
Addressed in #29
